# Generated by Django 3.2.12 on 2024-02-07 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_auto_20240206_1633'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='item',
            table='items',
        ),
    ]
