# Generated by Django 3.2.12 on 2024-02-07 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_alter_item_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='item',
            table='Items',
        ),
    ]
